import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Button, Container } from "@material-ui/core";
import { makeStyles } from "@material-ui/core";
import { TaskItem, TaskList } from "../components";

import { useEffect, useState } from "react";

const useStyles = makeStyles({
  box: {
    backgroundColor: "#00FF00",
    width: "100px",
    height: "100px",
  },
  // container: {
  //   margin: "auto",
  //   width: "500px",
  //   height: "400px",
  // },
});

export default function Home() {
  const classes = useStyles();
  return (
    ///re-rendering
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <Container className={classes.container}> */}
        <TaskList></TaskList>
        {/* </Container> */}
        {/* <div className={classes.box}>
          <p>1: {count}</p>
          <Button onClick={onClick}>+</Button>
        </div>
        <div className={classes.box}>
          <p>2: {count2}</p>
          <Button onClick={onClick2}>+</Button>
        </div> */}
      </main>
    </div>
  );

  // const [count, setCount] = useState(0);
  // const [count2, setCount2] = useState(0);
  // const classes = useStyles();

  // useEffect(() => {
  //   //side-effect
  //   console.log("increment 1");
  // }, [count]);

  // useEffect(() => {
  //   console.log("increment 2");
  // }, [count2]);

  // const double = (x) => {
  //   return x * 2;
  // };

  // const onClick = () => {
  //   setCount(count + 1);
  // };
  // const onClick2 = () => {
  //   setCount2(count2 + 1);
  // };
}
